package inventorysystem;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KL_Schweizer
 */
public class StoreConfigurationFrame extends javax.swing.JFrame {

    MainFrame mainFrame;
    
    DefaultTableModel dtm;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table_store = new javax.swing.JTable();
        button_configStocks = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        table_store.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_store.setSelectionBackground(new java.awt.Color(177, 0, 0));
        table_store.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table_store.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_store.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_store.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table_store);

        button_configStocks.setText("Configure Stocks");
        button_configStocks.setFocusable(false);
        button_configStocks.setRequestFocusEnabled(false);

        button_delete.setText("-");
        button_delete.setFocusable(false);
        button_delete.setRequestFocusEnabled(false);

        button_add.setText("+");
        button_add.setFocusable(false);
        button_add.setRequestFocusEnabled(false);
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_configStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_configStocks)
                    .addComponent(button_delete)
                    .addComponent(button_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        AddStore as = new AddStore();
        as.openFrame(mainFrame);
        as.setVisible(true);
        int x = (mainFrame.getWidth() - as.getWidth()) / 2;
        int y = (mainFrame.getHeight() - as.getHeight()) / 2;
        as.setLocation(x,y);
    }//GEN-LAST:event_button_addActionPerformed
    
    private void createColumns()
    {
        dtm = new DefaultTableModel(0,0)
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        dtm.addColumn("Store");
        dtm.addColumn("Address");
        table_store.setModel(dtm);
    }
    public void openFrame(MainFrame mainFrame)
    {
        this.mainFrame = mainFrame;
        initComponents();
        createColumns();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_configStocks;
    private javax.swing.JButton button_delete;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_store;
    // End of variables declaration//GEN-END:variables
}
